# Generated by Django 4.2.4 on 2023-11-24 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0005_alter_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='blocked_users',
            field=models.ManyToManyField(to='tournaments.userprofile'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='nameUser',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
