# Generated by Django 4.2.4 on 2023-11-24 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0006_tournament_blocked_users_alter_userprofile_nameuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='total_teams',
            field=models.IntegerField(null=True),
        ),
    ]
