# Generated by Django 4.2.4 on 2023-11-24 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0007_tournament_total_teams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='blocked_users',
            field=models.ManyToManyField(null=True, to='tournaments.userprofile'),
        ),
    ]
