# Generated by Django 4.2.4 on 2023-11-24 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0008_alter_tournament_blocked_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='blocked_users',
            field=models.ManyToManyField(blank=True, to='tournaments.userprofile'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='total_teams',
            field=models.IntegerField(),
        ),
    ]
