# Generated by Django 4.2.4 on 2023-11-24 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0009_alter_tournament_blocked_users_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
